name: Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    name: Gradle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: fleshgrinder/setup-java@1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: check
        cache-read-only: true
