name: Publish Release

on:
  push:
    tags-ignore:
    - '*-SNAPSHOT'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gradle:
    name: Gradle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: fleshgrinder/setup-java@1
    - name: Run Gradle
      uses: gradle/gradle-build-action@v2
      env:
        ORG_GRADLE_PROJECT_version: ${{ github.ref_name }}
      with:
        arguments: publish
        gradle-home-cache-cleanup: true
